In [1]:
import pandas as pd

## Task 1: Import JSON File into pandas

In [2]:
iris_json = pd.read_json("iris.json")
iris_json.head()

         class  petallength  petalwidth  sepallength  sepalwidth
0  Iris-setosa          1.4         0.2          5.1         3.5
1  Iris-setosa          1.4         0.2          4.9         3.0
2  Iris-setosa          1.3         0.2          4.7         3.2
3  Iris-setosa          1.5         0.2          4.6         3.1
4  Iris-setosa          1.4         0.2          5.0         3.6

## Task 1: Import xls file into pandas

In [3]:
iris_excel = pd.read_excel("iris.xls", header=1)
iris_excel

,Unnamed: 0,Sepal Length (cm),Sepal Width (cm),Petal Length (cm),Petal Width (cm),Class,Unnamed: 6,Unnamed: 7,alpha,obj,Unnamed: 10,Unnamed: 11
0,NaN,7.0,3.2,4.7,1.4,Iris-versicolor,NaN,0.0,0.0,0.0,0,1
1,NaN,6.4,3.2,4.5,1.5,Iris-versicolor,NaN,0.0,NaN,NaN,0,1
2,NaN,6.9,3.1,4.9,1.5,Iris-versicolor,NaN,0.0,NaN,NaN,0,1
3,NaN,5.5,2.3,4.0,1.3,Iris-versicolor,NaN,0.0,NaN,NaN,0,1
4,NaN,6.5,2.8,4.6,1.5,Iris-versicolor,NaN,NaN,NaN,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
95,NaN,4.8,3.0,1.4,0.3,Iris-setosa,NaN,NaN,NaN,NaN,0,1
96,NaN,5.1,3.8,1.6,0.2,Iris-setosa,NaN,NaN,NaN,NaN,0,1
97,NaN,4.6,3.2,1.4,0.2,Iris-setosa,NaN,NaN,NaN,NaN,0,1
98,NaN,5.3,3.7,1.5,0.2,Iris-setosa,NaN,NaN,NaN,NaN,0,1
99,NaN,5.0,3.3,1.4,0.2,Iris-setosa,NaN,NaN,NaN,NaN,0,1

In [4]:
iris_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         0 non-null      float64
 1   Sepal Length (cm)  100 non-null    float64
 2   Sepal Width (cm)   100 non-null    float64
 3   Petal Length (cm)  100 non-null    float64
 4   Petal Width (cm)   100 non-null    float64
 5   Class              100 non-null    object
 6   Unnamed: 6         0 non-null      float64
 7   Unnamed: 7         4 non-null      float64
 8   alpha              1 non-null      float64
 9   obj                1 non-null      float64
 10  Unnamed: 10        100 non-null    int64
 11  Unnamed: 11        100 non-null    int64
dtypes: float64(9), int64(2), object(1)
memory usage: 9.5+ KB

In [5]:
iris_excel.columns

Index(['Unnamed: 0', 'Sepal Length (cm)', 'Sepal Width (cm)',
       'Petal Length (cm)', 'Petal Width (cm)', 'Class', 'Unnamed: 6',
       'Unnamed: 7', 'alpha', 'obj', 'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')

In [6]:
iris_excel.drop(iris_excel.columns[[0, 6, 7, 8, 9, 10, 11]], axis = 1, inplace=True)
iris_excel.head()

,Sepal Length (cm),Sepal Width (cm),Petal Length (cm),Petal Width (cm),Class
0,7.0,3.2,4.7,1.4,Iris-versicolor
1,6.4,3.2,4.5,1.5,Iris-versicolor
2,6.9,3.1,4.9,1.5,Iris-versicolor
3,5.5,2.3,4.0,1.3,Iris-versicolor
4,6.5,2.8,4.6,1.5,Iris-versicolor

In [7]:
iris_excel = iris_excel[['Class', 'Sepal Length (cm)', 'Sepal Width (cm)', 'Petal Length (cm)', 'Petal Width (cm)']]
iris_excel.head()

,Class,Sepal Length (cm),Sepal Width (cm),Petal Length (cm),Petal Width (cm)
0,Iris-versicolor,7.0,3.2,4.7,1.4
1,Iris-versicolor,6.4,3.2,4.5,1.5
2,Iris-versicolor,6.9,3.1,4.9,1.5
3,Iris-versicolor,5.5,2.3,4.0,1.3
4,Iris-versicolor,6.5,2.8,4.6,1.5

## Task 2: Import HTML into dataframe

In [8]:
url = "https://en.wikipedia.org/wiki/World_population"
data = pd.read_html("https://en.wikipedia.org/wiki/World_population")
pop = data[8]

In [9]:
pop

,Year,Population,Yearly change,Net change,Density(pop/km2),Urban Population,Urban popÂ %
0,2020,7795000000,1.1%,81331000,52,4378900000,56%
1,2019,7713468000,1.1%,82377000,52,4299439000,56%
2,2018,7631091000,1.1%,83232000,51,4219817000,55%
3,2017,7547859000,1.1%,83837000,51,4140189000,55%
4,2016,7464022000,1.1%,84225000,50,4060653000,54%
5,2015,7379797000,1.2%,84506000,50,3981498000,54%
6,2014,7295291000,1.2%,84709000,49,3902832000,53%
7,2013,7210582000,1.2%,84754000,48,3824990000,53%
8,2012,7125828000,1.2%,84634000,48,3747843000,52%
9,2011,7041194000,1.2%,84371000,47,3671424000,52%
10,2010,6956824000,1.2%,84057000,47,3594868000,51%
11,2009,6872767000,1.2%,83678000,47,3516830000,51%
12,2008,6789089000,1.2%,83142000,46,3439719000,50%
13,2007,6705947000,1.2%,82429000,45,3363610000,50%
14,2006,6623518000,1.3%,81611000,44,3289446000,50%
15,2005,6541907000,1.3%,80748000,44,3215906000,49%
16,2004,6461159000,1.3%,79974000,43,3143045000,48%
17,2003,6381185000,1.3%,79412000,43,3071744000,48%
18,2002,6301773000,1.3%,79147000,42,3001808000,47%
19,2001,6222627000,1.3%,79133000,42,2933079000,47%
20,2000,6143494000,1.3%,79255000,41,2868308000,46%

# Task 3: Tasks and scopes that would be helpful to develop a customer complain management system using Machine Learning Algorithms.

> - 1. What are the top 10 complaints against products and sub-products?
> - 2. What are the top 20 issues and sub issues?
> - 3. In which month did most complaints occur and on which day of the week are most complaint received?
> - 4. Which state received the largest number of complaints?
> - 5. Which company received most complaints?

## 1. What are the top 10 complaints against products and sub-products?

In [18]:
df_original = pd.read_csv("Consumer_Complaints.csv")
df_original.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,3/21/2017,Credit reporting,NaN,Incorrect information on credit report,Information is not mine,NaN,Company has responded to the consumer and the ...,EXPERIAN DELAWARE GP,TX,77075,Older American,NaN,Phone,3/21/2017,Closed with non-monetary relief,Yes,No,2397100
1,4/19/2017,Debt collection,"Other (i.e. phone, health club, etc.)",Disclosure verification of debt,Not disclosed as an attempt to collect,NaN,NaN,"Security Credit Services, LLC",IL,60643,NaN,NaN,Web,4/20/2017,Closed with explanation,Yes,No,2441777
2,4/19/2017,Credit card,NaN,Other,NaN,NaN,Company has responded to the consumer and the ...,"CITIBANK, N.A.",IL,62025,NaN,NaN,Referral,4/20/2017,Closed with explanation,Yes,No,2441830
3,4/14/2017,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,Company believes it acted appropriately as aut...,"Shellpoint Partners, LLC",CA,90305,NaN,NaN,Referral,4/14/2017,Closed with explanation,Yes,No,2436165
4,4/19/2017,Credit card,NaN,Credit determination,NaN,NaN,Company has responded to the consumer and the ...,U.S. BANCORP,LA,70571,NaN,NaN,Postal mail,4/21/2017,Closed with explanation,Yes,No,2441726

In [19]:
len(df_original.Issue.unique())

158

In [20]:
df = df_original.copy()
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,3/21/2017,Credit reporting,NaN,Incorrect information on credit report,Information is not mine,NaN,Company has responded to the consumer and the ...,EXPERIAN DELAWARE GP,TX,77075,Older American,NaN,Phone,3/21/2017,Closed with non-monetary relief,Yes,No,2397100
1,4/19/2017,Debt collection,"Other (i.e. phone, health club, etc.)",Disclosure verification of debt,Not disclosed as an attempt to collect,NaN,NaN,"Security Credit Services, LLC",IL,60643,NaN,NaN,Web,4/20/2017,Closed with explanation,Yes,No,2441777
2,4/19/2017,Credit card,NaN,Other,NaN,NaN,Company has responded to the consumer and the ...,"CITIBANK, N.A.",IL,62025,NaN,NaN,Referral,4/20/2017,Closed with explanation,Yes,No,2441830
3,4/14/2017,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,Company believes it acted appropriately as aut...,"Shellpoint Partners, LLC",CA,90305,NaN,NaN,Referral,4/14/2017,Closed with explanation,Yes,No,2436165
4,4/19/2017,Credit card,NaN,Credit determination,NaN,NaN,Company has responded to the consumer and the ...,U.S. BANCORP,LA,70571,NaN,NaN,Postal mail,4/21/2017,Closed with explanation,Yes,No,2441726

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777959 entries, 0 to 777958
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Date received                 777959 non-null  object
 1   Product                       777959 non-null  object
 2   Sub-product                   542822 non-null  object
 3   Issue                         777959 non-null  object
 4   Sub-issue                     320986 non-null  object
 5   Consumer complaint narrative  157865 non-null  object
 6   Company public response       197884 non-null  object
 7   Company                       777959 non-null  object
 8   State                         772056 non-null  object
 9   ZIP code                      772001 non-null  object
 10  Tags                          109264 non-null  object
 11  Consumer consent provided?    288311 non-null  object
 12  Submitted via                 777959 non-null  object
 13  Date sent to company          777959 non-null  object
 14  Company response to consumer  777959 non-null  object
 15  Timely response?              777959 non-null  object
 16  Consumer disputed?            768414 non-null  object
 17  Complaint ID                  777959 non-null  int64
 18  product_frequency             777959 non-null  int64
dtypes: int64(2), object(17)
memory usage: 112.8+ MB

In [40]:
df.isnull().sum()

Date received                        0
Product                              0
Sub-product                     235137
Issue                                0
Sub-issue                       456973
Consumer complaint narrative    620094
Company public response         580075
Company                              0
State                             5903
ZIP code                          5958
Tags                            668695
Consumer consent provided?      489648
Submitted via                        0
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Consumer disputed?                9545
Complaint ID                         0
product_frequency                    0
dtype: int64

In [21]:
df["product_frequency"] = 0

In [22]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,product_frequency
0,3/21/2017,Credit reporting,NaN,Incorrect information on credit report,Information is not mine,NaN,Company has responded to the consumer and the ...,EXPERIAN DELAWARE GP,TX,77075,Older American,NaN,Phone,3/21/2017,Closed with non-monetary relief,Yes,No,2397100,0
1,4/19/2017,Debt collection,"Other (i.e. phone, health club, etc.)",Disclosure verification of debt,Not disclosed as an attempt to collect,NaN,NaN,"Security Credit Services, LLC",IL,60643,NaN,NaN,Web,4/20/2017,Closed with explanation,Yes,No,2441777,0
2,4/19/2017,Credit card,NaN,Other,NaN,NaN,Company has responded to the consumer and the ...,"CITIBANK, N.A.",IL,62025,NaN,NaN,Referral,4/20/2017,Closed with explanation,Yes,No,2441830,0
3,4/14/2017,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,Company believes it acted appropriately as aut...,"Shellpoint Partners, LLC",CA,90305,NaN,NaN,Referral,4/14/2017,Closed with explanation,Yes,No,2436165,0
4,4/19/2017,Credit card,NaN,Credit determination,NaN,NaN,Company has responded to the consumer and the ...,U.S. BANCORP,LA,70571,NaN,NaN,Postal mail,4/21/2017,Closed with explanation,Yes,No,2441726,0

In [49]:
df.groupby("Product").count().sort_values(by="product_frequency", ascending=False)

,Date received,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,product_frequency
Product,,,,,,,,,,,,,,,,,,
Mortgage,228167,228167,228167,0,32000,43425,228167,226630,226615,31416,56784,228167,228167,228167,228167,226887,228167,228167
Debt collection,148016,148016,148016,148016,38741,38682,148016,147198,147189,23974,68937,148016,148016,148016,148016,145839,148016,148016
Credit reporting,140405,0,140405,140405,30319,54019,140405,139932,139931,17396,67133,140405,140405,140405,140405,140405,140405,140405
Credit card,89189,0,89189,0,18276,20857,89189,88473,88471,13508,31091,89189,89189,89189,89189,89189,89189,89189
Bank account or service,86206,86206,86206,0,14500,24013,86206,84650,84643,11826,23443,86206,86206,86206,86206,86206,86206,86206
Student loan,33044,33044,33044,27322,10176,3827,33044,32842,32842,2568,17636,33044,33044,33044,33044,32511,33044,33044
Consumer Loan,31591,31591,31591,0,9029,7707,31591,31411,31411,5225,14705,31591,31591,31591,31591,31591,31591,31591
Payday loan,5543,0,5543,0,1695,1086,5543,5523,5523,929,2898,5543,5543,5543,5543,5543,5543,5543
Money transfers,5355,5355,5355,0,1437,665,5355,5155,5156,1026,2247,5355,5355,5355,5355,5355,5355,5355
Prepaid card,3817,3817,3817,0,1404,978,3817,3774,3774,464,2255,3817,3817,3817,3817,3817,3817,3817
"Credit reporting, credit repair services, or other personal consumer reports",3490,3490,3490,3435,0,1437,3490,3433,3428,425,531,3490,3490,3490,3490,0,3490,3490
Other financial service,1051,1051,1051,0,272,396,1051,1031,1031,212,468,1051,1051,1051,1051,1051,1051,1051
Credit card or prepaid card,919,919,919,910,0,380,919,894,886,138,92,919,919,919,919,0,919,919
Checking or savings account,664,664,664,664,0,269,664,624,616,80,34,664,664,664,664,2,664,664
Vehicle loan or lease,221,221,221,221,0,46,221,216,216,36,12,221,221,221,221,0,221,221
"Payday loan, title loan, or personal loan",140,140,140,13,0,38,140,138,137,28,12,140,140,140,140,0,140,140
"Money transfer, virtual currency, or money service",123,123,123,0,0,50,123,115,115,13,16,123,123,123,123,0,123,123
Virtual currency,18,18,18,0,16,9,18,17,17,0,17,18,18,18,18,18,18,18

In [54]:
# Finding top 10 complaints against products

df.groupby("Product").count().sort_values(by="product_frequency", ascending=False).iloc[0:10, -1]

Product
Mortgage                   228167
Debt collection            148016
Credit reporting           140405
Credit card                 89189
Bank account or service     86206
Student loan                33044
Consumer Loan               31591
Payday loan                  5543
Money transfers              5355
Prepaid card                 3817
Name: product_frequency, dtype: int64

In [44]:
len(df['Sub-product'].unique())

76

In [48]:
len(df.Product.unique())

18

In [53]:
# Finding top 10 complaints against sub-products

df.groupby(["Product", "Sub-product"]).count().sort_values(by="product_frequency", ascending=False).iloc[0:10, -1]

Product                  Sub-product
Mortgage                 Other mortgage                            86622
                         Conventional fixed mortgage               70607
Bank account or service  Checking account                          59048
Debt collection          Other (i.e. phone, health club, etc.)     44534
                         I do not know                             30326
                         Credit card                               28698
Mortgage                 Conventional adjustable mortgage (ARM)    25382
                         FHA mortgage                              24823
Student loan             Non-federal student loan                  22280
Debt collection          Medical                                   21202
Name: product_frequency, dtype: int64

## 2. What are the top 20 issues and sub issues?

In [56]:
# Finding top 20 Issues

df.groupby("Issue").count().sort_values(by="product_frequency", ascending=False).iloc[0:20, -1]

Issue
Loan modification,collection,foreclosure    112316
Incorrect information on credit report      102667
Loan servicing, payments, escrow account     77334
Cont'd attempts collect debt not owed        60698
Account opening, closing, or management      37962
Disclosure verification of debt              30796
Communication tactics                        24073
Deposits and withdrawals                     22850
Dealing with my lender or servicer           17610
Application, originator, mortgage broker     17221
Credit reporting company's investigation     16880
Managing the loan or lease                   15358
Billing disputes                             15135
Other                                        14775
Problems caused by my funds being low        11845
False statements or representation           11819
Unable to get credit report/credit score     10855
Improper contact or sharing of info          10068
Problems when you are unable to pay           9388
Settlement process and costs                  8938
Name: product_frequency, dtype: int64

In [57]:
# Finding top 20 sub-issues

df.groupby(["Issue", "Sub-issue"]).count().sort_values(by="product_frequency", ascending=False).iloc[0:20, -1]

Issue                                     Sub-issue
Incorrect information on credit report    Account status                              37057
Cont'd attempts collect debt not owed     Debt is not mine                            36740
Incorrect information on credit report    Information is not mine                     32372
Disclosure verification of debt           Not given enough info to verify debt        21809
Cont'd attempts collect debt not owed     Debt was paid                               16625
Communication tactics                     Frequent or repeated calls                  14637
Incorrect information on credit report    Account terms                               10991
False statements or representation        Attempted to collect wrong amount            9116
Incorrect information on credit report    Public record                                8875
                                          Personal information                         7528
Disclosure verification of debt           Right to dispute notice not received         7189
Unable to get credit report/credit score  Problem getting my free annual report        6467
Credit reporting company's investigation  No notice of investigation status/result     6416
                                          Problem with statement of dispute            5907
Incorrect information on credit report    Reinserted previously deleted info           5844
Dealing with my lender or servicer        Trouble with how payments are handled        5655
Improper use of my credit report          Report improperly shared by CRC              5242
Improper contact or sharing of info       Talked to a third party about my debt        5053
Cont'd attempts collect debt not owed     Debt resulted from identity theft            4908
Communication tactics                     Threatened to take legal action              4711
Name: product_frequency, dtype: int64

## 3. In which month did most complaints occur and on which day of the week are most complaint received?

In [60]:
df['Date received']  = pd.to_datetime(df['Date received'])

In [63]:
df['Year']  = df['Date received'].dt.year

In [66]:
df['Month']  = df['Date received'].dt.month_name()

In [68]:
df['Day']  = df['Date received'].dt.day_name()

In [71]:
df['Day'].value_counts()

Wednesday    150675
Tuesday      149269
Thursday     144373
Friday       128248
Monday       125474
Saturday      45787
Sunday        34133
Name: Day, dtype: int64

In [72]:
df["Year"].value_counts()

2016    191525
2015    168527
2014    153051
2013    108213
2017     81737
2012     72370
2011      2536
Name: Year, dtype: int64

In [73]:
df["Month"].value_counts()

March        79811
April        75588
January      73076
February     69841
August       63099
May          62027
October      61614
July         61408
September    59521
June         58988
December     58162
November     54824
Name: Month, dtype: int64

## 4. Which state received the largest number of complaints?

In [87]:
df.State.value_counts()[:1]

CA    111765
Name: State, dtype: int64

## 5. Which company received most complaints?

In [89]:
df.Company.value_counts()[:1]

BANK OF AMERICA, NATIONAL ASSOCIATION    66314
Name: Company, dtype: int64

# Task 5: Five problems around us that can be solved using data science.

> - *Unemployment solution:* If we have data for every unemployed guy and girl. Like in what field they are good at, what kind of work they are looking for. Then we can supply human power to every company and we can even solve daily basis problems for the individual families. We can make a model that predicts what kind of job will be available in the future then it Will be easy for us to train them accordingly.

> - *Finding diseases:* If we have the data for patient's disease and the dose of medicine given to him or her then we can build a model that can predict the dose of medicine for that disesses.

> - *Prevention of road accidents:* It is one of the biggest challenge for our country. If we get the video footage before the accident happened we can built a model which can alert us the passenger's and the car's activity before the accident took place.

> - *Birth control:* Data of new birth in every area help us to understand the reason of growth in population. After fidding the data to the model we can understand the characteristics of the area. Which later can help us for prediction.

> - *Increase customer in a particular area:* Since every area has it's particular customer and every customer's characteristics is different human brain can not figure out the hidden difference and choice of every customer. This is a good area to train our model for better understanding the customer behaviour.